# Generated by Django 4.2.7 on 2023-11-13 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familita')),
                ('fathers_name', models.CharField(max_length=100, verbose_name='Otasini ismi')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=300)),
                ('faculty', models.CharField(max_length=500, verbose_name='Fakultet')),
                ('field_of_education', models.CharField(max_length=500, verbose_name="Ta'lim yo'nalishi")),
                ('group', models.CharField(max_length=500, verbose_name='Guruhi')),
                ('education_stage', models.IntegerField(verbose_name="Ta'lim bosqichi")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
